### ISSUE TITLE
cannot use smoothing, fails with syntax error

### ISSUE THREAD

**Issue by parsarian** [derhuerst/svg-radar-chart#16]
I used this code to generate similar chart as show bellow but the result was have so visual differences:
```js
const radar = require('svg-radar-chart');
const stringify = require('virtual-dom-stringify');

var fs = require('fs');



    const result = [1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 2, 1, 1, 2, 2, 0, 0];
    var final = sort(result);
    console.log(final);

    const chart = radar({
        // columns
        a: 'a',
        b: 'b',
        c: 'c',
        d: 'd',
        e: 'e',
        f: 'f',
        g: 'g',
        h: 'h'
    }, [
        // data
        {
            class: 'sab1',
            a: final[0] / 10,
            b: final[1] / 10,
            c: final[2] / 10,
            d: final[3] / 10,
            e: final[4] / 10,
            f: final[5] / 10,
            g: final[6] / 10,
            h: final[7] / 10
        }

    ]);
    const svg = `
<svg version="1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
	<style>
		.axis {
			stroke-width: .2;
		}
		.scale {
			stroke-width: .3;
		}
		.shape {
			fill-opacity: .3;
		}
		.shape:hover {
			fill-opacity: .6;
		}
	</style>
	${stringify(chart)}
</svg>
`;
    
    //process.stdout.write(svg);
    var fname = 'test' + '.svg';
    fs.writeFile(fname, svg, function (err) {
        if (err) {
            return console.log(err);
        }
        console.log("The file was saved!");
    });

    function sort(result) {

        var newr = [
            [0],
            [0],
            [0],
            [0],
            [0],
            [0],
            [0],
            [0]
        ];

        var j = 0;
        var p = 0;
        for (var i = 0; i != 7; i++) {
            var ip = 0;
            for (var k = j; k != 7; k++) {
                newr[ip].push(result[p]);
                p++;
                ip++;
            }
            j++;
        }
        for (var i = 0; i != 7; i++) {
            ip = i + 1;
            for (var k = i + 1; k != 8; k++) {
                newr[ip].unshift(result[p]);
                p++;
                ip++;
            }

        }
        return subtotall(newr);
    }

    function subtotall(newr) {
        var total = [0, 0, 0, 0, 0, 0, 0, 0];
        for (var i = 0; i < 8; i++) {
            for (var j = 0; j < 8; j++) {
                if (newr[i][j] == 1) {
                    total[i] = total[i] + 1;
                }
            }
        }
        for (var i = 0; i < 8; i++) {
            for (var j = 0; j < 8; j++) {
                if (newr[j][i] == 2) {
                    total[i] = total[i] + 1;
                }
            }
        }
        return total;
    }
```

Preferred Chart:

![image](https://user-images.githubusercontent.com/25129775/39377999-5723ac10-4a6c-11e8-8e8f-40b1b40ec559.png)

Output result:

![image](https://user-images.githubusercontent.com/25129775/39378071-882035ae-4a6c-11e8-8ede-3f10ddf367b1.png)

**Comment by derhuerst** [comment]
Your code looks mostly unrelated to the fact that the rendering is weird. Also, I couldn't run it (`subtotall` is not defined). Please try to provide a minimal working example.

**Comment by parsarian** [comment]
Excuse me I was forgot to a add it . I have updated code. I also tried to use smooth but it has also problem with d3-path.

**Comment by derhuerst** [comment]
So with your code, all elements of the chart are there, but invisible. They will be visible if you adapt the styles to e.g. these:

```css
.axis {
	stroke-width: .2;
	stroke: #aaa;
}
.scale {
	stroke-width: .3;
	stroke: #aaa;
}
.shape {
	fill-opacity: .5;
	fill: #2c3e50;
}
.shape:hover {
	fill-opacity: .7;
}
```

I will change the readme to be more helpful.

**Comment by derhuerst** [comment]
> I also tried to use smooth but it has also problem with d3-path.

Give me your code, the specific error and the stack trace.

**Comment by parsarian** [comment]
Great thanks, one part of my problem has solved bu your great help. I've tried `smooth`.  

I add this lines to above code and :
`const smoothing = require('svg-radar-chart/smoothing');`

and changed radar API function to this:
```
const chart = radar({   //col
        a: 'a',
        b: 'b',            
        c: 'c',
        d: 'd',
        e: 'e',
        f: 'f',
        g: 'g',        
        h: 'h'
    }, [        // data
        {
            class: 'sab1',
            a: final[0] / 10,
            b: final[1] / 10,
            c: final[2] / 10,
            d: final[3] / 10,
            e: final[4] / 10,
            f: final[5] / 10,
            g: final[6] / 10,
            h: final[7] / 10
        }
    ],{
	size: 120, // size of the chart (including captions)
	axes: true, // show axes?
	scales: 2, // show scale circles?
	captions: true, // show captions?
	captionsPosition: 1.2, // where on the axes are the captions?
	smoothing: smoothing(.2), // shape smoothing function
	axisProps: () => ({className: 'axis'}),
	scaleProps: () => ({className: 'scale', fill: 'none'}),
	shapeProps: () => ({className: 'shape'}),
	captionProps: () => ({
		className: 'caption',
		textAnchor: 'middle', fontSize: 3,
		fontFamily: 'sans-serif'
	})
});
```

**The error is this :**

```

(function (exports, require, module, __filename, __dirname) { import {path} from "d3-path";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```
![image](https://user-images.githubusercontent.com/25129775/39415078-3a43ba9c-4c54-11e8-8c14-96d34cc07fa3.png)

**Comment by parsarian** [comment]
One more question is that how to insert empty Axis between A and B like : 
![image](https://user-images.githubusercontent.com/25129775/39421951-9ec676c2-4c80-11e8-818c-4b1ba47253f2.png)

I tried such this, but it was asking for value:
```
    const chart = radar({
        a: 'a',
        a1: ' ',      
        b: 'b',
        b1: ' ',        
        c: 'c',
        c1: ' ',
        d: 'd',
        d1: ' ',
        e: 'e',
        e1: ' ',
        f: 'f',
        f1: ' ',
        g: 'g',
        g1: ' ',
        h: 'h',
        h1: ' '
    }, [
        // data
        {
            class: 'sab1',
            a: final[0] / 10,
            b: final[1] / 10,
            c: final[2] / 10,
            d: final[3] / 10,
            e: final[4] / 10,
            f: final[5] /  10,
            g: final[6] / 10,
            h: final[7] / 10,
        }
    ]);


```

**Comment by derhuerst** [comment]
In `6105877` I have fixed this. Published as `svg-radar-chart@0.2.1`.

The bug had happened because `d3-shape`, a dependency of this lib, changed underneath, and I used it in an unsupported way.

**Comment by derhuerst** [comment]
> I tried such this, but it was asking for value:

Yes, if you add fields to the `columns` object, it will expect a corresponding number at each item in `data`. You could add `0` as value in each item.

**Comment by parsarian** [comment]
Adding 0 to guide `columns `will change the chart shape.
those blue point (which is crossing with secondary columns ) and green area has different meaning of red line areas. iwas thinking to generate a zero template area and adding chart to tempale.

![image](https://user-images.githubusercontent.com/25129775/39425053-d000abf0-4c8e-11e8-8d6d-55aee28afe0b.png)

**Comment by derhuerst** [comment]
> Adding 0 to guide `columns` will change the chart shape.

In this case I can't help any further unfortunately. I think the feature you want is too niche, so I won't add it, sorry.
